import type { SettingsCategory, SettingsState } from "@/components/settings/types"
import { SIDEBAR_COLOR_OPTIONS, THEME_OPTIONS } from "@/composables/useAppTheme"
import type { DrawbridgeUser } from "@/drawbridge/types"

export function createSettingsState(user: DrawbridgeUser): SettingsState {
  return {
    accountName: user.name,
    accountEmail: user.email,
    preferredName: user.name,
    selectedAvatarTone: "blue",
    userId: "usr_drawbridge_admin",
    enterKeyStartsNewLine: true,
    language: "zh-CN",
    numberFormat: "zh-CN",
    bidirectionalTextControl: false,
    weekStartsOnMonday: true,
    dateFormat: "yyyy-MM-dd",
    autoTimezoneByLocation: true,
    timezone: "Asia/Shanghai",
    themeMode: "system",
    sidebarColor: "neutral",
    compactTables: false,
    reducedMotion: false,
    showCommandHints: true,
    usageDiagnostics: false,
    cookiePreference: "necessary",
    viewHistoryVisible: true,
    profileDiscoverable: true,
    memberDefaultRole: "operator",
    inviteApprovalRequired: true,
    allowExternalMembers: false,
    apiBaseUrl: "/api",
    deployTarget: "static",
    publicBasePath: "/",
  }
}

export function createSettingsCategories(user: DrawbridgeUser): SettingsCategory[] {
  const avatarFallback = user.avatarFallback ?? user.name.slice(0, 2).toUpperCase()

  return [
    {
      key: "me",
      group: "account",
      label: "我",
      description: "管理当前账号的显示信息。",
      pageTitle: "我",
      pageDescription: "管理你的档案、头像和模板内账号展示。",
      icon: "ri-user-3-line",
      avatarFallback,
      sections: [],
    },
    {
      key: "preferences",
      group: "account",
      label: "偏好设置",
      description: "主题、日期、语言和界面密度。",
      pageTitle: "偏好设置",
      pageDescription: "这些选项展示真实后台常见偏好项，可替换为远程用户配置。",
      icon: "ri-equalizer-line",
      sections: [
        {
          key: "appearance",
          title: "外观",
          description: "控制主题、侧边栏色板和常用界面密度。",
          items: [
            {
              key: "theme",
              label: "主题",
              description: "支持跟随系统、浅色和深色模式。",
              type: "select",
              modelKey: "themeMode",
              options: THEME_OPTIONS.map(option => ({
                label: option.label,
                value: option.value,
              })),
            },
            {
              key: "sidebar-color",
              label: "侧边栏色板",
              description: "保留 buildguard-admin 的侧栏主题变量，项目可继续扩展。",
              type: "select",
              modelKey: "sidebarColor",
              options: SIDEBAR_COLOR_OPTIONS.map(option => ({
                label: option.label,
                value: option.value,
                color: option.color,
                darkColor: option.darkColor,
              })),
            },
            {
              key: "compact-tables",
              label: "紧凑表格",
              description: "让数据密集页面使用更短行高。",
              type: "toggle",
              modelKey: "compactTables",
            },
            {
              key: "reduced-motion",
              label: "减少动效",
              description: "适合长时间使用或对动效敏感的团队。",
              type: "toggle",
              modelKey: "reducedMotion",
            },
          ],
        },
        {
          key: "locale",
          title: "地区与输入",
          description: "日期、数字、时区和输入习惯。",
          items: [
            {
              key: "language",
              label: "语言",
              description: "模板默认使用中文文案，真实项目可接入 i18n。",
              type: "select",
              modelKey: "language",
              options: [
                { label: "简体中文", value: "zh-CN" },
                { label: "English", value: "en-US" },
              ],
            },
            {
              key: "date-format",
              label: "日期格式",
              description: "用于表格、详情和筛选面板展示。",
              type: "select",
              modelKey: "dateFormat",
              options: [
                { label: "2026-06-01", value: "yyyy-MM-dd" },
                { label: "2026/06/01", value: "yyyy/MM/dd" },
                { label: "06/01/2026", value: "MM/dd/yyyy" },
              ],
            },
            {
              key: "timezone-auto",
              label: "自动时区",
              description: "接入用户资料服务后可由后端下发。",
              type: "toggle",
              modelKey: "autoTimezoneByLocation",
            },
            {
              key: "timezone",
              label: "时区",
              description: "影响审计日志、日历和服务端分页查询时间。",
              type: "input",
              modelKey: "timezone",
              placeholder: "Asia/Shanghai",
            },
          ],
        },
        {
          key: "privacy",
          title: "隐私与诊断",
          description: "展示模板级隐私选项边界。",
          items: [
            {
              key: "profile-discoverable",
              label: "允许团队成员看到个人资料",
              description: "用于团队通讯录、审批流等功能。",
              type: "toggle",
              modelKey: "profileDiscoverable",
            },
            {
              key: "view-history",
              label: "记录最近访问",
              description: "可用于全局搜索和最近打开列表。",
              type: "toggle",
              modelKey: "viewHistoryVisible",
            },
            {
              key: "usage-diagnostics",
              label: "使用诊断",
              description: "仅用于展示，不会发送任何真实数据。",
              type: "toggle",
              modelKey: "usageDiagnostics",
            },
          ],
        },
      ],
    },
    {
      key: "apps",
      group: "feature",
      label: "应用",
      description: "集成、发布和 webhook 占位页。",
      pageTitle: "应用",
      pageDescription: "展示设置页中的特色应用管理页面，数据来自本地 mock。",
      icon: "ri-apps-2-line",
      sections: [],
    },
    {
      key: "members",
      group: "workspace",
      label: "成员与角色",
      description: "成员、角色和权限组管理。",
      pageTitle: "成员与角色",
      pageDescription: "用于演示后台模板常见的成员和角色表格模式。",
      icon: "ri-team-line",
      sections: [],
    },
    {
      key: "developer",
      group: "admin",
      label: "菜单与权限",
      description: "菜单、按钮和 API 资源配置。",
      pageTitle: "菜单与权限",
      pageDescription: "从 Drawbridge 配置生成菜单示例，并展示按钮/API 资源边界。",
      icon: "ri-code-box-line",
      sections: [],
    },
    {
      key: "business-presets",
      group: "feature",
      label: "业务预设",
      description: "字典、状态和标签类配置。",
      pageTitle: "业务预设",
      pageDescription: "保留原项目的字典维护体验，但内容改为可复用模板示例。",
      icon: "ri-list-settings-line",
      sections: [],
    },
    {
      key: "inspection-items",
      group: "feature",
      label: "检查配置",
      description: "检查项、分类和模板配置。",
      pageTitle: "检查配置",
      pageDescription: "保留特色页的三层配置结构，用 mock 数据展示可扩展方式。",
      icon: "ri-shield-check-line",
      sections: [],
    },
  ]
}
